ruby:
  stage: test
  trigger:
    project: EmilienMottet/exercism-ruby-sol
    strategy: depend

elixir:
  stage: test
  trigger:
    project: EmilienMottet/exercism-elixir-sol
    strategy: depend

erlang:
  stage: test
  trigger:
    project: EmilienMottet/exercism-erlang-sol
    strategy: depend
